### ISSUE TITLE
star only direct dependencies

### ISSUE THREAD

**Issue by splitbrain** [symfony/thanks#18]
It seems the plugin currently sends stars to all dependencies of a project, including the dependencies of the the libraries you actually added to your composer file.

It would be nice if there would be an option to star the explicit dependencies only.

**Comment by nicolas-grekas** [comment]
Don't you think transitive dependencies deserve a thank also? You direct dependencies wouldn't exist without their own dependencies.

![image](https://user-images.githubusercontent.com/243674/34260240-776c33cc-e665-11e7-9d3d-51fc73e4374a.png)

Here is a happy package maintainer. I believe this command should be generous and transitive.

**Comment by splitbrain** [comment]
The problem is that my stars are also some kind of endorsement. I happily endorse the libraries I use, but I don't know anything about their dependencies. Yes, I'm thankful they exist and made the libs of my choice possible, but I don't necessarily want to star them.

Simple example: I happily endorse phpunit because it's what I use for testing and I believe everyone should check it out. However I now also starred sebastianbergmann/resource-operations of which I don't even know what it does.

I'm happy with this plugin working as is by default, but having an option to skip sub-dependencies would be useful, I believe.

**Comment by localheinz** [comment]
I agree with @splitbrain, I would suggest to only endorse *direct* dependencies, not indirect dependencies. Adding a library is a conscious decision, whereas a dependency required by a dependency is - hopefully -  a conscious decision of *their* maintainers.

**Comment by nicolas-grekas** [comment]
Then one will require a "metapackage", or a "symfony-pack", and stars will go to them, although they don't contain any code...

**Comment by localheinz** [comment]
But still, sending a star to a repository that I have never taken a look at sends a wrong message, at least from my point of view. I would personally never star a repository that I don't actually find awesome, and I don't find things awesome that I haven't even taken a look at.

**Comment by nicolas-grekas** [comment]
I respect your pov. Yet I think we build the tool as it is on purpose. Yes, this maybe not universal thinking.
I'm not sure I would change the original idea. But of course you can do your own plugin (or just not run the command).
Note that this is not a rebuttal, just an opinionated pov on the topic :)

**Comment by localheinz** [comment]
Ha, no worries!

It's a great idea, @nicolas-grekas, and I like it!

**Comment by javiereguiluz** [comment]
During the past days, when Nico was developing this project, I agreed with what @splitbrain and @localheinz are saying ... but now I think differently. Why did I change my mind? Because of this reasoning:

1) You don't want to star an indirect dependency because maybe it's not good, because you don't even know it exists, because you don't want to endorse it without analyzing it first, etc.
2) However, if you remove that indirect dependency, your project simply stops working ... and your company stops earning money (... and maybe you get fired 😭).
3) So, if something is so important that even your product/company depends on it, shouldn't at least get a GitHub star? You won't spend time or money giving them a star, and considering that you are probably not going to help them reporting issues of contributing pull requests, the least you can do si to give them a free GitHub star.

**Comment by splitbrain** [comment]
I totally get that argument. However, stars have a history. They were used before this plugin and people have build other stuff on top of them. For example, every project I star will end up in a linkblog on my website... Each of those entries is tweeted to twitter... Each of my tweets is synced to Facebook... So in a way my reputation (whatever that may be worth) is linked to a star. So I don't really feel comfortable with attaching that to things I've never heard about.

Regarding 2. - it seems the plugin currently stars production *and* devel dependencies (correct me if I'm wrong). The devel dependencies of the used libraries aren't even things I rely on.

**Comment by javiereguiluz** [comment]
@splitbrain I see ... and I understand that you cannot use this command because of the way you use GitHub stars.

Dev requirements are a bit different ... but they are still essential. You "cannot" develop the project without dev requirements ... so you can't implement features or fix bugs ... so the project will fail ... the company will stop earning money ... and you'll get fired again 😭

**Comment by splitbrain** [comment]
well, I need *my* dev requirements and am happy to endorse them. But I don't care what my dependencies use as a test framework. I might even disagree with their choices (but I am not sure if this plugin stars dev requirements of requirements and that's a different topic).

Anyway I'd be happy about an option but I do understand your point of view. Thanks for the inspiration anyway!

**Comment by nicolas-grekas** [comment]
Devs of devs are not starred since they are not installed in your project. Thanks for raising the topic.
