### ISSUE TITLE
Update documentation to use "suggest" rather than "require --dev"

### ISSUE THREAD

**Issue by pfrenssen** [symfony/thanks#48]
Currently the documentation suggests to add the project to a `composer.json` file by adding it as a development requirement.

Wouldn't it be better to propose to use Composer's "[suggest](https://getcomposer.org/doc/04-schema.md#suggest)" feature instead?

1. This will also expose the package to other projects that have the package as a depency. `require-dev` is only shown to people that install the package itself.
2. `require-dev` is intended for listing the packages that are strictly required for development. It's hard to justify symfony/thanks as a strict requirement.

**Comment by nicolas-grekas** [comment]
Hello,
Thanks you for the suggestions. Yet, this would defeat the purpose of the plugin, by making the command harder to discover and use for everyone. The plugin doesn't do anything unless you actively use it.

**Comment by JorisVanEijden** [comment]
Sounds like the purpose of the plugin is to act like a virus and spread as far and wide as possible while not giving people a choice.

The reason this is not part of composer itself is so that people can decide for themselves if they want to use it: https://twitter.com/seldaek/status/947100791814443008
By adding this plugin as a requirement to as many packages and frameworks as possible you're not spreading the love, but taking away choice and consent.

Spread the joy through `suggest` in stead. Let people decide if they want this plugin installed or not in the polite way rather than being so pushy about it.
